* Music Downloader

App to help downloading top Punjabi songs

** Use cases

*** John

John executes the program, and a terminal opens which shows progress of the program. After
a while terminal stops with "Scraping Finished" message, and John's default browser opens
with a page which shows all the top Punjabi songs.

John see a nice collage of media images of songs which John can download. John hovers his
mouse cursor on the image, and a "Play" icon appears. John clicks on the play icon, and the
song starts playing. Icon changes to pause icon. John dislikes the song, so he clicks on
pause icon and it stops playing.

John likes another song, and want to download it. So he click on the "Download" icon in
bottom right corner of song's image, and the song downloads. A "Check" icon appears on the
song John downloaded.

** Specifications

*** Scraping
- Start with a list of "Start urls"
  - http://djpunjab.com/page/top20.html?type=week
  - https://mr-johal.com/topTracks.php?cat=Single%20Track
- Extract ~((song-name, artist), [link])~ pairs
- Create unique list of ~((song-name, artist), [link])~ pairs
- Print list

*** Data Cleaning

*** User Interface

**** CLI

**** Web UI
